// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analyses": {
            "post": {
                "security": [
                    {
                        "APIToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analyses"
                ],
                "summary": "Submit an analysis",
                "parameters": [
                    {
                        "description": "Analysis request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_analyzer.SubmitAnalysisRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Analysis persisted",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_analyzer.AnalysisEnvelope"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API token",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Extraction not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "409": {
                        "description": "Extraction not in done status",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Analysis storage unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "502": {
                        "description": "LLM upstream failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/analyses/{extraction_id}": {
            "get": {
                "security": [
                    {
                        "APIToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analyses"
                ],
                "summary": "Get an analysis by extraction id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Extraction id",
                        "name": "extraction_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Analysis found",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_analyzer.AnalysisEnvelope"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API token",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Analysis not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Analysis storage unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/arxiv/fetch": {
            "get": {
                "security": [
                    {
                        "APIToken": []
                    }
                ],
                "description": "Triggers an arXiv fetch + persist cycle. No body, no query params.\nReturns the fetched entries with per-entry is_new derived from\nwhether persistence inserted a new row for that paper.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Arxiv"
                ],
                "summary": "Fetch latest arXiv entries",
                "responses": {
                    "200": {
                        "description": "Fetched entries",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_arxiv.FetchEnvelope"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API token",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Catalogue unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "502": {
                        "description": "Upstream arXiv returned a non-success or malformed response",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "504": {
                        "description": "Upstream arXiv unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/extractions": {
            "post": {
                "security": [
                    {
                        "APIToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extractions"
                ],
                "summary": "Submit an extraction",
                "parameters": [
                    {
                        "description": "Extraction request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_extraction.SubmitExtractionRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Extraction enqueued",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_extraction.ExtractionStatusEnvelope"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API token",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Catalogue unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/extractions/{id}": {
            "get": {
                "security": [
                    {
                        "APIToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extractions"
                ],
                "summary": "Get extraction status by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Extraction id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Extraction state",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_extraction.ExtractionStatusEnvelope"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API token",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Extraction not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Catalogue unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/papers": {
            "get": {
                "security": [
                    {
                        "APIToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Papers"
                ],
                "summary": "List all persisted papers",
                "responses": {
                    "200": {
                        "description": "Paper catalogue",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_paper.PaperListEnvelope"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API token",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Catalogue unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/papers/{source}/{source_id}": {
            "get": {
                "security": [
                    {
                        "APIToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Papers"
                ],
                "summary": "Get a paper by source + source_id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source identifier (e.g. 'arxiv')",
                        "name": "source",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Source-local paper id (e.g. arXiv id)",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paper found",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller_paper.PaperEnvelope"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API token",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Paper not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Catalogue unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/sources": {
            "get": {
                "security": [
                    {
                        "APIToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sources"
                ],
                "summary": "List all sources",
                "responses": {
                    "200": {
                        "description": "Sources",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller.SourceListEnvelope"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API token",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "APIToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sources"
                ],
                "summary": "Create a source",
                "parameters": [
                    {
                        "description": "Source to create",
                        "name": "source",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_domain_source.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created source",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller.SourceEnvelope"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON body or validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API token",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "409": {
                        "description": "Source URL already exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/sources/{id}": {
            "get": {
                "security": [
                    {
                        "APIToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sources"
                ],
                "summary": "Get a source by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Source",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller.SourceEnvelope"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API token",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Source not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "APIToken": []
                    }
                ],
                "tags": [
                    "Sources"
                ],
                "summary": "Delete a source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Deleted"
                    },
                    "401": {
                        "description": "Missing or invalid API token",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Source not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "APIToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sources"
                ],
                "summary": "Update a source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "source",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_domain_source.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated source",
                        "schema": {
                            "$ref": "#/definitions/internal_http_controller.SourceEnvelope"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON body or validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API token",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Source not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_yoavweber_research-monitor_backend_internal_domain_source.CreateRequest": {
            "type": "object",
            "required": [
                "kind",
                "name",
                "url"
            ],
            "properties": {
                "kind": {
                    "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_domain_source.Kind"
                },
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_yoavweber_research-monitor_backend_internal_domain_source.Kind": {
            "type": "string",
            "enum": [
                "rss",
                "api"
            ],
            "x-enum-varnames": [
                "KindRSS",
                "KindAPI"
            ]
        },
        "github_com_yoavweber_research-monitor_backend_internal_domain_source.Response": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "kind": {
                    "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_domain_source.Kind"
                },
                "last_fetched_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_yoavweber_research-monitor_backend_internal_domain_source.UpdateRequest": {
            "type": "object",
            "properties": {
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_yoavweber_research-monitor_backend_internal_http_common.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_yoavweber_research-monitor_backend_internal_http_common.ErrorEnvelope": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_http_common.Error"
                }
            }
        },
        "internal_http_controller.SourceEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_domain_source.Response"
                }
            }
        },
        "internal_http_controller.SourceListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_yoavweber_research-monitor_backend_internal_domain_source.Response"
                    }
                }
            }
        },
        "internal_http_controller_analyzer.AnalysisEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_http_controller_analyzer.AnalysisResponse"
                }
            }
        },
        "internal_http_controller_analyzer.AnalysisResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "extraction_id": {
                    "type": "string"
                },
                "long_summary": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "prompt_version": {
                    "type": "string"
                },
                "short_summary": {
                    "type": "string"
                },
                "thesis_angle_flag": {
                    "type": "boolean"
                },
                "thesis_angle_rationale": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_analyzer.SubmitAnalysisRequest": {
            "type": "object",
            "required": [
                "extraction_id"
            ],
            "properties": {
                "extraction_id": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_arxiv.EntryResponse": {
            "type": "object",
            "properties": {
                "abs_url": {
                    "type": "string"
                },
                "abstract": {
                    "type": "string"
                },
                "authors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "is_new": {
                    "type": "boolean"
                },
                "pdf_url": {
                    "type": "string"
                },
                "primary_category": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                },
                "submitted_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_arxiv.FetchEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_http_controller_arxiv.FetchResponse"
                }
            }
        },
        "internal_http_controller_arxiv.FetchResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_http_controller_arxiv.EntryResponse"
                    }
                },
                "fetched_at": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_extraction.ExtractionStatusEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_http_controller_extraction.ExtractionStatusResponse"
                }
            }
        },
        "internal_http_controller_extraction.ExtractionStatusResponse": {
            "type": "object",
            "properties": {
                "body_markdown": {
                    "type": "string"
                },
                "failure_message": {
                    "type": "string"
                },
                "failure_reason": {
                    "description": "Failure branch — populated iff status == failed.",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/internal_http_controller_extraction.MetadataDTO"
                },
                "source_id": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "description": "Artifact branch — populated iff status == done. Metadata is a pointer\nso the entire object disappears from JSON when nil.",
                    "type": "string"
                }
            }
        },
        "internal_http_controller_extraction.MetadataDTO": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "word_count": {
                    "type": "integer"
                }
            }
        },
        "internal_http_controller_extraction.SubmitExtractionRequest": {
            "type": "object",
            "required": [
                "pdf_path",
                "source_id",
                "source_type"
            ],
            "properties": {
                "pdf_path": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                }
            }
        },
        "internal_http_controller_paper.PaperEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_http_controller_paper.PaperResponse"
                }
            }
        },
        "internal_http_controller_paper.PaperListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_http_controller_paper.PaperListResponse"
                }
            }
        },
        "internal_http_controller_paper.PaperListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "papers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_http_controller_paper.PaperResponse"
                    }
                }
            }
        },
        "internal_http_controller_paper.PaperResponse": {
            "type": "object",
            "properties": {
                "abs_url": {
                    "type": "string"
                },
                "abstract": {
                    "type": "string"
                },
                "authors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pdf_url": {
                    "type": "string"
                },
                "primary_category": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                },
                "submitted_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "APIToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Research Monitor API",
	Description:      "HTTP API for the research monitor (arXiv ingestion + paper catalogue).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
